In [37]:
import pandas as pd
import numpy as np
# from matplotlib import pyplot as plt

In [3]:
orders = r"C:/Users/hp/Downloads/retail_order/orders.csv"
retail_orders = pd.read_csv(orders)

In [4]:
retail_orders.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [5]:
retail_orders.shape

(9994, 16)

In [6]:
retail_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [7]:
retail_orders.head(5)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [8]:
retail_orders.describe()

,Order Id,Postal Code,cost price,List Price,Quantity,Discount Percent
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,201.189714,229.756854,3.789574,3.484090
std,2885.163629,32063.693350,537.743203,623.245839,2.225110,1.114211
min,1.000000,1040.000000,0.000000,0.000000,1.000000,2.000000
25%,2499.250000,23223.000000,20.000000,20.000000,2.000000,2.000000
50%,4997.500000,56430.500000,50.000000,50.000000,3.000000,3.000000
75%,7495.750000,90008.000000,180.000000,210.000000,5.000000,4.000000
max,9994.000000,99301.000000,18110.000000,22640.000000,14.000000,5.000000

In [9]:
retail_orders['Sub Category'].value_counts()

Sub Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [10]:
retail_orders['Sub Category'].nunique()

17

In [11]:
retail_orders['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

## **1. Descriptive & Business Overview**

### 1.1 Total Revenue, Total Profit, and Average profit margin across all orders

In [12]:
retail_orders.head(3)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5

1. Total Revenue

In [13]:
retail_orders['selling price'] = retail_orders['List Price'] - ((retail_orders['List Price'] * retail_orders['Discount Percent'])/100)
retail_orders['revenue'] = retail_orders['selling price'] * retail_orders['Quantity']
total_revenue = retail_orders['revenue'].sum()

In [14]:
retail_orders['cost'] = retail_orders['cost price'] * retail_orders['Quantity']
retail_orders['profit'] = retail_orders['revenue'] - retail_orders['cost']
total_profit = retail_orders['profit'].sum()

In [15]:
avg_profit_per_order = retail_orders['profit'].mean()
avg_profit_per_unit = retail_orders['profit'].sum() / retail_orders['Quantity'].sum()
retail_orders['profit_margin'] = (retail_orders['profit'] / retail_orders['revenue']) * 100
avg_profit_margin = retail_orders['profit_margin'].mean()

In [16]:
print(f'The total revenue is: {total_revenue}')
print(f'The total profit is: {total_profit}')
print(f'The Average Profit per Order is: {avg_profit_per_order}')
print(f'The Average Profit per Unit is: {avg_profit_per_unit}')
print(f'The Average Profit Margin is: {total_profit}')

The total revenue is: 11079328.200000001
The total profit is: 1039928.2000000001
The Average Profit per Order is: 104.05525315189114
The Average Profit per Unit is: 27.458300108256545
The Average Profit Margin is: 1039928.2000000001

### 1.2 What is the distribution of orders and quantity sold across segments?

In [17]:
segment_distribution = (
    retail_orders.groupby('Segment').agg(order_count=('Order Id', 'nunique'),
                                         total_quantity_sold=('Quantity', 'sum'))
)

In [18]:
segment_distribution

             order_count  total_quantity_sold
Segment
Consumer            5191                19521
Corporate           3020                11608
Home Office         1783                 6744

### 1.3 Which Categories and Sub-Categories generate the highest revenue and profit?

In [19]:
category_level = retail_orders.groupby('Category').agg(total_revenue=('revenue','sum'),
                                                       total_profit=('profit','sum')).sort_values('total_revenue', ascending=False)
category_level

                 total_revenue  total_profit
Category
Technology           3934910.7      379720.7
Furniture            3720742.4      342782.4
Office Supplies      3423675.1      317425.1

In [20]:
sub_category_level = retail_orders.groupby('Sub Category').agg(total_revenue=('revenue','sum'),
                                                       total_profit=('profit','sum')).sort_values('total_revenue', ascending=False)
sub_category_level

              total_revenue  total_profit
Sub Category
Chairs            1604415.7      153905.7
Phones            1568578.5      139498.5
Tables            1102172.2       98522.2
Storage           1061125.3       96105.3
Binders            976402.8       98802.8
Machines           883535.3       91545.3
Accessories        847632.0       79412.0
Copiers            635164.9       69264.9
Bookcases          576400.8       51270.8
Appliances         528152.6       54582.6
Furnishings        437753.7       39083.7
Paper              375602.6       32362.6
Supplies           194112.5       14402.5
Art                131702.2       10412.2
Envelopes           71639.7        6109.7
Labels              68208.8        4188.8
Fasteners           16728.6         458.6

## **2. Geographic & Regional Performance**

### 2.1 Which Region is the most profitable overall?

In [21]:
retail_orders.head(5)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,...,Product Id,cost price,List Price,Quantity,Discount Percent,selling price,revenue,cost,profit,profit_margin
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,FUR-BO-10001798,240,260,2,2,254.8,509.6,480,29.6,5.808477
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,FUR-CH-10000454,600,730,3,3,708.1,2124.3,1800,324.3,15.266205
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,...,OFF-LA-10000240,10,10,2,5,9.5,19.0,20,-1.0,-5.263158
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,...,FUR-TA-10000577,780,960,5,2,940.8,4704.0,3900,804.0,17.091837
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,...,OFF-ST-10000760,20,20,2,5,19.0,38.0,40,-2.0,-5.263158

In [42]:
retail_orders['Discount Percent'].max()

np.int64(5)

In [22]:
region_profit = retail_orders.groupby('Region')['profit'].sum().sort_values()
region_profit

Region
South      202743.6
Central    236121.2
East       295773.8
West       305289.6
Name: profit, dtype: float64

In [23]:
region_profit_with_agg = retail_orders.groupby('Region').agg(profit=('profit','sum')).sort_values('profit', ascending=False)
region_profit_with_agg

           profit
Region
West     305289.6
East     295773.8
Central  236121.2
South    202743.6

### 2.2 Identify cities with high revenue but low or negative profit. What could this indicate?

In [24]:
city_profit = retail_orders.groupby('City').agg(city_profit_amt=('profit','sum'), revenue=('revenue','sum')).sort_values('city_profit_amt')
city_profit

               city_profit_amt    revenue
City
Frisco                   -13.2      286.8
Waukesha                 -12.5      237.5
Sheboygan                -12.3      237.7
La Quinta                -10.0      190.0
Redwood City              -9.6      230.4
...                        ...        ...
San Francisco          48472.6   522682.6
Seattle                50765.7   577155.7
Philadelphia           52619.3   548049.3
Los Angeles            73294.8   842734.8
New York City         103852.6  1218342.6

[531 rows x 2 columns]

In [25]:
city_profit[city_profit['city_profit_amt'] < 0].sort_values('revenue', ascending=False).head(5)

                 city_profit_amt  revenue
City
Canton                      -0.2   3709.8
West Palm Beach             -2.5    427.5
Frisco                     -13.2    286.8
Bellevue                    -8.0    272.0
Grapevine                   -7.8    252.2

### 2.3 Compare average profit margin across regions. Are some regions consistently underperforming?

In [27]:
retail_orders['Order Date'] = pd.to_datetime(retail_orders['Order Date'])
retail_orders['order month'] = retail_orders['Order Date'].dt.to_period('M')

In [30]:
monthly_profit_margin = retail_orders.groupby(['order month', 'Region']).agg(total_profit=('profit', 'sum'), total_revenue=('revenue', 'sum'))
monthly_profit_margin

                     total_profit  total_revenue
order month Region
2022-01     Central        5306.3        64896.3
            East          11905.2       122995.2
            South          6713.6        68703.6
            West          19596.2       180836.2
2022-02     Central        5745.5        66365.5
...                           ...            ...
2023-11     West          10383.4       109283.4
2023-12     Central       13287.0       142327.0
            East          14152.8       148772.8
            South          8607.4        79577.4
            West           7171.7       121171.7

[96 rows x 2 columns]

In [33]:
monthly_profit_margin['profit_margin'] = (monthly_profit_margin['total_profit'] / monthly_profit_margin['total_revenue']) * 100

In [34]:
monthly_profit_margin

                     total_profit  total_revenue  profit_margin
order month Region
2022-01     Central        5306.3        64896.3       8.176583
            East          11905.2       122995.2       9.679402
            South          6713.6        68703.6       9.771831
            West          19596.2       180836.2      10.836437
2022-02     Central        5745.5        66365.5       8.657360
...                           ...            ...            ...
2023-11     West          10383.4       109283.4       9.501352
2023-12     Central       13287.0       142327.0       9.335544
            East          14152.8       148772.8       9.513029
            South          8607.4        79577.4      10.816388
            West           7171.7       121171.7       5.918626

[96 rows x 3 columns]

In [ ]:
# this is order wise / row wise profit margin, which means this is profit margin for every single order placed. we dont want this, we want monthly profit margin

region_profit_margin = retail_orders.groupby('Region').agg(avg_profit_margin=('profit_margin','mean')).sort_values('avg_profit_margin', ascending=False)
region_profit_margin

         avg_profit_margin
Region
South             5.410577
East              5.398080
West              5.378048
Central           4.998748

## **3. Discount & Pricing Impact Analysis**

### 3.1 Does higher discount percentage lead to higher average revenue?

In [45]:
retail_orders.head(5)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,...,List Price,Quantity,Discount Percent,selling price,revenue,cost,profit,profit_margin,order month,discount_bucket
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,260,2,2,254.8,509.6,480,29.6,5.808477,2023-03,1-2%
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,730,3,3,708.1,2124.3,1800,324.3,15.266205,2023-08,2-3%
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,...,10,2,5,9.5,19.0,20,-1.0,-5.263158,2023-01,4-5%
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,...,960,5,2,940.8,4704.0,3900,804.0,17.091837,2022-06,1-2%
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,...,20,2,5,19.0,38.0,40,-2.0,-5.263158,2022-07,4-5%

In [44]:
# Discount buckets
retail_orders['discount_bucket'] = pd.cut(
    retail_orders['Discount Percent'], bins=[0, 1, 2, 3, 4, 5], 
    labels=['0-1%', '1-2%', '2-3%', '3-4%', '4-5%'],
    include_lowest=True
)

In [46]:
discount_revenue_analysis = retail_orders.groupby('discount_bucket').agg(avg_revenue=('revenue','mean'))
discount_revenue_analysis

C:\Users\hp\AppData\Local\Temp\ipykernel_23952\3216916943.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  discount_revenue_analysis = retail_orders.groupby('discount_bucket').agg(avg_revenue=('revenue','mean'))

                 avg_revenue
discount_bucket
0-1%                     NaN
1-2%             1057.180341
2-3%             1111.642132
3-4%             1095.787905
4-5%             1171.910156

There appears to be a moderate positive relationship between discount percentage and average revenue, with higher discount ranges generally associated with higher average revenue

### 3.2 Which discount ranges produce the best profit margins?

In [ ]:
discount_profit_margin = retail_orders.groupby('discount_bucket').agg(avg_profit_margin=('profit_margin','mean')).sort_values('avg_profit_margin', ascending=False)

C:\Users\hp\AppData\Local\Temp\ipykernel_23952\1086284867.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  discount_profit_margin = retail_orders.groupby('discount_bucket').agg(avg_profit_margin=('profit_margin','mean')).sort_values('avg_profit_margin', ascending=False)

In [48]:
discount_profit_margin

                 avg_profit_margin
discount_bucket
1-2%                      6.999681
2-3%                      5.738527
3-4%                      4.715573
4-5%                      3.698295
0-1%                           NaN

Lower discount ranges generate the strongest profit margins, while higher discount ranges reduce profitability despite slightly improving revenue. This suggests that aggressive discounting may not be financially sustainable.

### 3.3 Are there products or categories that consistently incur losses due to aggressive discounting?

In [ ]:
# Step 1 — Filter high discount orders

high_discount_threshold = 4

high_discount_df = retail_orders[retail_orders['Discount Percent'] >= high_discount_threshold]

#### Category wise Loss

In [68]:
# Step 2 — Monthly profit by sub-category

monthly_loss = high_discount_df.groupby(['order month', 'Category']).agg(total_profit=('profit','sum'),
                                                                    order_count=('Order Id', 'count'),
                                                                    avg_discount=('Discount Percent','mean')).reset_index()
monthly_loss

   order month         Category  total_profit  order_count  avg_discount
0      2022-01        Furniture        6308.6           51      4.549020
1      2022-01  Office Supplies        9337.9          112      4.473214
2      2022-01       Technology        6321.8           31      4.548387
3      2022-02        Furniture        4849.9           41      4.536585
4      2022-02  Office Supplies        7971.1          131      4.480916
..         ...              ...           ...          ...           ...
67     2023-11  Office Supplies        3094.6          129      4.441860
68     2023-11       Technology        5549.2           45      4.444444
69     2023-12        Furniture        3599.3           40      4.500000
70     2023-12  Office Supplies        2935.9          118      4.491525
71     2023-12       Technology        5043.9           47      4.446809

[72 rows x 5 columns]

In [69]:
# Step 3 — Keep only loss-making months

loss_months = monthly_loss[monthly_loss['total_profit'] < 0]

In [ ]:
# Step 4 — Count how many months each sub-category was in loss

consistent_losers_category = loss_months.groupby('Category').agg(loss_months=('order month','count'),
                                                                     total_loss=('total_profit', 'sum'),
                                                                     avg_discount=('avg_discount','mean')).sort_values('loss_months', ascending=False)

consistent_losers_category

Empty DataFrame
Columns: [loss_months, total_loss, avg_discount]
Index: []

#### Product / Sub-Category wise Loss

In [75]:
# Step 2 — Monthly profit by sub-category

monthly_loss_sub_category = high_discount_df.groupby(['order month', 'Sub Category']).agg(total_profit=('profit','sum'),
                                                                    order_count=('Order Id', 'count'),
                                                                    avg_discount=('Discount Percent','mean')).reset_index()
monthly_loss_sub_category

    order month Sub Category  total_profit  order_count  avg_discount
0       2022-01  Accessories        1647.9           12      4.666667
1       2022-01   Appliances         728.7           11      4.363636
2       2022-01          Art         -41.7           14      4.571429
3       2022-01      Binders        4671.0           28      4.357143
4       2022-01    Bookcases         122.9            2      4.500000
..          ...          ...           ...          ...           ...
394     2023-12        Paper         463.5           31      4.451613
395     2023-12       Phones        2233.8           23      4.521739
396     2023-12      Storage        1758.4           20      4.350000
397     2023-12     Supplies          25.4            5      4.400000
398     2023-12       Tables        1180.4            5      4.400000

[399 rows x 5 columns]

In [76]:
# Step 3 — Keep only loss-making months

loss_months_sub_category = monthly_loss_sub_category[monthly_loss['total_profit'] < 0]

In [77]:
# Step 4 — Count how many months each sub-category was in loss

consistent_losers_sub_category = loss_months_sub_category.groupby('Sub Category').agg(loss_months=('order month','count'),
                                                                     total_loss=('total_profit', 'sum'),
                                                                     avg_discount=('avg_discount','mean')).sort_values('loss_months', ascending=False)

consistent_losers_sub_category

              loss_months  total_loss  avg_discount
Sub Category
Fasteners              17      -172.5      4.492484
Labels                  7      -129.2      4.511132
Envelopes               4       -40.4      4.395833
Supplies                3       -53.1      4.440476
Art                     3       -62.1      4.505291
Copiers                 1        -8.0      5.000000
Machines                1        -2.7      4.500000

## **4. Product-Level Performance**

### 4.1 What are the top 10 most profitable products?

In [ ]:
top_10_profitable = (retail_orders.groupby('Sub Category')).agg(total_profit=('profit','sum'),
                                                                total_revenue=('revenue','sum'),
                                                                order_count=('Order Id', 'count'),
                                                                avg_profit_margin=('profit_margin','mean')).sort_values('total_profit', ascending=False).head(10)

top_10_profitable

              total_profit  total_revenue  order_count  avg_profit_margin
Sub Category
Chairs            153905.7      1604415.7          617           9.385787
Phones            139498.5      1568578.5          889           8.139257
Binders            98802.8       976402.8         1523           2.748713
Tables             98522.2      1102172.2          319           9.623959
Storage            96105.3      1061125.3          846           7.528388
Machines           91545.3       883535.3          115           8.387673
Accessories        79412.0       847632.0          775           8.371025
Copiers            69264.9       635164.9           68           8.808554
Appliances         54582.6       528152.6          466           7.432231
Bookcases          51270.8       576400.8          228           9.499421

### 4.2  Which products are sold at a net loss and should be reviewed or discontinued?

In [86]:
retail_orders.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent', 'selling price', 'revenue', 'cost', 'profit',
       'profit_margin', 'order month', 'discount_bucket'],
      dtype='object')

In [85]:
product_profitability = retail_orders.groupby('Sub Category').agg(total_profit=('profit','sum'),
                                                                total_revenue=('revenue','sum'),
                                                                order_count=('Order Id', 'count'),
                                                                avg_profit_margin=('profit_margin','mean')).reset_index()
product_profitability

   Sub Category  total_profit  total_revenue  order_count  avg_profit_margin
0   Accessories       79412.0       847632.0          775           8.371025
1    Appliances       54582.6       528152.6          466           7.432231
2           Art       10412.2       131702.2          796           1.211251
3       Binders       98802.8       976402.8         1523           2.748713
4     Bookcases       51270.8       576400.8          228           9.499421
5        Chairs      153905.7      1604415.7          617           9.385787
6       Copiers       69264.9       635164.9           68           8.808554
7     Envelopes        6109.7        71639.7          254           3.358672
8     Fasteners         458.6        16728.6          217          -1.164181
9   Furnishings       39083.7       437753.7          957           4.631774
10       Labels        4188.8        68208.8          364           0.377047
11     Machines       91545.3       883535.3          115           8.387673
12        Paper       32362.6       375602.6         1370           3.224212
13       Phones      139498.5      1568578.5          889           8.139257
14      Storage       96105.3      1061125.3          846           7.528388
15     Supplies       14402.5       194112.5          190           3.416589
16       Tables       98522.2      1102172.2          319           9.623959

In [84]:
# Filter only net loss products

net_loss_products = (product_profitability[product_profitability['total_profit'] < 0]).sort_values('total_profit')
net_loss_products

Empty DataFrame
Columns: [Sub Category, total_profit, total_revenue, order_count, avg_profit_margin]
Index: []

### 4.3 Compare average selling price and profit margin across Categories.

In [88]:
retail_orders.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent', 'selling price', 'revenue', 'cost', 'profit',
       'profit_margin', 'order month', 'discount_bucket'],
      dtype='object')

In [89]:
category_analysis = retail_orders.groupby('Category').agg(avg_selling_price=('selling price','mean'),
                                                          avg_profit_margin=('profit_margin','mean'),
                                                          total_revenue=('revenue','sum'),
                                                          order_count=('Order Id','count')).round(2).sort_values('avg_profit_margin', ascending=False)

category_analysis

,avg_selling_price,avg_profit_margin,total_revenue,order_count
Category,,,,
Technology,436.86,8.28,3934910.7,1847
Furniture,337.27,7.32,3720742.4,2121
Office Supplies,115.11,3.56,3423675.1,6026

## **5. Advanced Pandas – apply() & Lambda Logic**

### 5.1 Create a profit_label column:
    High Profit (≥ 500)
    Medium Profit (100–499)
    Low Profit (0–99)
    Loss (< 0)

### 5.2 Flag orders with high discount and negative profit using a boolean column.

### 5.3 Create a shipping_priority label based on ship mode (Urgent / Standard / Low Priority).

### 5.4 Build a composite business_score using profit margin, quantity, and discount thresholds.

### 5.5 Identify Premium vs Regular orders using selling price and profit margin criteria.

## **6. Window & Analytical Operations (SQL-style Pandas)**

### 6.1 Rank products by revenue within each category.

### 6.2 Compute running cumulative revenue by region over time.

### 6.3 Compare each order’s revenue against the regional average revenue using transform().

## **7.  Pivoting, Reshaping & Aggregation**

### 7.1 Create a pivot table showing revenue by Region and Category.

### 7.2 Convert the pivoted data back into a long-format DataFrame.

### 7.3 Build a category-level summary table with:

    Total revenue
    Total profit
    Average discount
    Order count

## **8. Time-Series Analysis**

### 8.1 What is the monthly revenue trend over time?

### 8.2 Calculate month-over-month revenue growth percentage.

### 8.3 Identify months with declining revenue and investigate possible causes.

## **9. Data Quality & Performance Mindset**

### 9.1 Validate that no orders have negative revenue or invalid profit margins.

### 9.2 Optimize memory usage by converting suitable columns to categorical types.